//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class acabado
    {
        public string clave { get; set; }
        public string acabado1 { get; set; }
        public Nullable<double> neto_recto { get; set; }
        public Nullable<double> neto_curvo { get; set; }
    }
}
