//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos_reporte
    {
        public int id { get; set; }
        public string concepto { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> alto { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> total { get; set; }
        public byte[] pic { get; set; }
        public string desc_p { get; set; }
    }
}
