//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class colores_aluminio
    {
        public int id { get; set; }
        public string clave { get; set; }
        public string color { get; set; }
        public string proveedor { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> costo_extra_ml { get; set; }
    }
}
