//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class copybox
    {
        public int id { get; set; }
        public Nullable<int> folio { get; set; }
        public Nullable<int> modulo_id { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> mano_obra { get; set; }
        public string dimensiones { get; set; }
        public string acabado_perfil { get; set; }
        public string claves_cristales { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string articulo { get; set; }
        public string linea { get; set; }
        public string diseño { get; set; }
        public string clave { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> largo { get; set; }
        public Nullable<int> alto { get; set; }
        public Nullable<double> flete { get; set; }
        public Nullable<double> utilidad { get; set; }
        public Nullable<double> desperdicio { get; set; }
        public string claves_otros { get; set; }
        public string claves_herrajes { get; set; }
        public byte[] pic { get; set; }
        public string claves_perfiles { get; set; }
        public Nullable<int> merge_id { get; set; }
        public Nullable<int> concept_id { get; set; }
        public string ubicacion { get; set; }
        public Nullable<int> sub_folio { get; set; }
        public Nullable<int> dir { get; set; }
        public string news { get; set; }
        public string new_desing { get; set; }
        public Nullable<int> orden { get; set; }
    }
}
