//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cotizaciones_local : DbContext
    {
        public cotizaciones_local()
            : base("name=cotizaciones_local")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<materiales_modulos> materiales_modulos { get; set; }
        public virtual DbSet<corte> cortes { get; set; }
        public virtual DbSet<cotizacione> cotizaciones { get; set; }
        public virtual DbSet<cristales_cotizados> cristales_cotizados { get; set; }
        public virtual DbSet<herrajes_cotizados> herrajes_cotizados { get; set; }
        public virtual DbSet<otros_cotizaciones> otros_cotizaciones { get; set; }
        public virtual DbSet<aluminio_cotizado> aluminio_cotizado { get; set; }
        public virtual DbSet<datos_reporte> datos_reporte { get; set; }
        public virtual DbSet<articulos_reporte> articulos_reporte { get; set; }
        public virtual DbSet<modulos_cotizaciones> modulos_cotizaciones { get; set; }
        public virtual DbSet<copybox> copyboxes { get; set; }
    }
}
