//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class cristales_cotizados
    {
        public Nullable<int> folio { get; set; }
        public string clave { get; set; }
        public string articulo { get; set; }
        public string lista { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> alto { get; set; }
        public string canteado { get; set; }
        public string biselado { get; set; }
        public string desconchado { get; set; }
        public string pecho_paloma { get; set; }
        public string perforado_media_pulgada { get; set; }
        public string perforado_una_pulgada { get; set; }
        public string perforado_dos_pulgadas { get; set; }
        public string grabado { get; set; }
        public string esmerilado { get; set; }
        public string tipo_venta { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> descuento { get; set; }
        public int id { get; set; }
        public string proveedor { get; set; }
        public Nullable<double> filo_muerto { get; set; }
        public string descripcion { get; set; }
    }
}
