//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class datos_reporte
    {
        public int id { get; set; }
        public string Cliente { get; set; }
        public string Nombre_Proyecto { get; set; }
        public string Folio { get; set; }
        public string Fecha { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> Total { get; set; }
        public string Forma_de_Pago { get; set; }
        public string email { get; set; }
    }
}
