//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class esquema
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> filas { get; set; }
        public Nullable<int> columnas { get; set; }
        public string diseño { get; set; }
        public string esquemas { get; set; }
        public Nullable<bool> marco { get; set; }
        public string grupo { get; set; }
    }
}
