//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class filas_borradas
    {
        public int id { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> folio { get; set; }
        public Nullable<int> articulo_id { get; set; }
    }
}
