//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class lista_precios_hojas
    {
        public string clave { get; set; }
        public string articulo { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> alto { get; set; }
        public Nullable<double> precio_hoja { get; set; }
        public string proveedor { get; set; }
        public string moneda { get; set; }
    }
}
