//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class listas_entities_pva : DbContext
    {
        public listas_entities_pva()
            : base("name=listas_entities_pva")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lista_costo_corte_e_instalado> lista_costo_corte_e_instalado { get; set; }
        public virtual DbSet<lista_precio_corte_e_instalado> lista_precio_corte_e_instalado { get; set; }
        public virtual DbSet<lista_precios_hojas> lista_precios_hojas { get; set; }
        public virtual DbSet<acabado> acabados { get; set; }
        public virtual DbSet<otro> otros { get; set; }
        public virtual DbSet<esquema> esquemas { get; set; }
        public virtual DbSet<herraje> herrajes { get; set; }
        public virtual DbSet<colores_aluminio> colores_aluminio { get; set; }
        public virtual DbSet<modulo> modulos { get; set; }
        public virtual DbSet<perfile> perfiles { get; set; }
        public virtual DbSet<paquete> paquetes { get; set; }
    }
}
