//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class modulos_articulos
    {
        public int id { get; set; }
        public string componente { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public string clave { get; set; }
        public string articulo { get; set; }
        public Nullable<double> cantidad { get; set; }
        public string ubicacion { get; set; }
        public Nullable<int> seccion { get; set; }
    }
}
