//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class modulo
    {
        public int id { get; set; }
        public string clave { get; set; }
        public string articulo { get; set; }
        public string linea { get; set; }
        public string clave_vidrio { get; set; }
        public string id_aluminio { get; set; }
        public string id_herraje { get; set; }
        public string id_otros { get; set; }
        public Nullable<int> secciones { get; set; }
        public string descripcion { get; set; }
        public string usuario { get; set; }
        public Nullable<int> id_diseño { get; set; }
        public Nullable<bool> cs { get; set; }
        public string parametros { get; set; }
        public string reglas { get; set; }
        public Nullable<bool> privado { get; set; }
    }
}
