//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfile
    {
        public int id { get; set; }
        public string clave { get; set; }
        public string articulo { get; set; }
        public string linea { get; set; }
        public string proveedor { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> ancho_perfil { get; set; }
        public Nullable<double> perimetro_dm2_ml { get; set; }
        public Nullable<double> crudo { get; set; }
        public Nullable<double> blanco { get; set; }
        public Nullable<double> hueso { get; set; }
        public Nullable<double> champagne { get; set; }
        public Nullable<double> gris { get; set; }
        public Nullable<double> negro { get; set; }
        public Nullable<double> brillante { get; set; }
        public Nullable<double> natural_1 { get; set; }
        public Nullable<double> madera { get; set; }
        public Nullable<double> kg_peso_lineal { get; set; }
        public string fecha { get; set; }
        public Nullable<double> chocolate { get; set; }
        public Nullable<double> acero_inox { get; set; }
        public Nullable<double> bronce { get; set; }
        public string moneda { get; set; }
    }
}
