//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class produccion_t
    {
        public int id { get; set; }
        public byte[] pic { get; set; }
        public string ubicacion { get; set; }
        public string medidas { get; set; }
        public string observaciones { get; set; }
        public string vista { get; set; }
        public string apertura { get; set; }
        public string descripcion { get; set; }
        public string aluminio { get; set; }
        public string cristal { get; set; }
        public string herrajes { get; set; }
        public string otros { get; set; }
        public Nullable<int> cantidad { get; set; }
    }
}
