//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Collections.Generic;
    
    public partial class propiedades_local
    {
        public int id { get; set; }
        public Nullable<int> folio_abierto { get; set; }
        public string nombre_cliente_abierto { get; set; }
        public Nullable<double> p_cristales { get; set; }
        public Nullable<double> p_aluminio { get; set; }
        public Nullable<double> p_herrajes { get; set; }
        public Nullable<double> p_otros { get; set; }
        public string proyecto_abierto { get; set; }
        public Nullable<double> desc_cotizacion { get; set; }
        public Nullable<double> utilidad_cotizacion { get; set; }
    }
}
