//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cristales_pva
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class localDateBaseEntities3 : DbContext
    {
        public localDateBaseEntities3()
            : base("name=localDateBaseEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<userLocal> userLocals { get; set; }
        public virtual DbSet<filas_borradas> filas_borradas { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<proveedore> proveedores { get; set; }
        public virtual DbSet<lineas_modulos> lineas_modulos { get; set; }
        public virtual DbSet<modulos_articulos> modulos_articulos { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<propiedade> propiedades { get; set; }
        public virtual DbSet<propiedades_local> propiedades_local { get; set; }
    }
}
